# fly.toml app configuration file generated for companionui-test on 2023-09-20T09:24:59+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "companion-ui-test"
primary_region = "arn"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
