# fly.toml app configuration file generated for companion-db-test on 2023-09-15T22:52:07+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "companion-db-test"
primary_region = "sea"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
